### ISSUE TITLE
Error running javascript file

### ISSUE THREAD

**Issue by sjayanna** [drnic/javascript-node.tmbundle#7]
This is the error message I got when I tried to run after installing this bundle.
This happened on Mountain Lion and textmate 1.5.11.

/private/tmp/temp_textmate.xYlVBQ:6 if(process.ENV.TM_FILENAME.match(/(.*)spec.js/)) { ^ TypeError: Cannot read property 'TM_FILENAME' of undefined at Object. (/private/tmp/temp_textmate.xYlVBQ:6:15) at Module._compile (module.js:449:26) at Object.Module._extensions..js (module.js:467:10) at Module.load (module.js:356:32) at Function.Module._load (module.js:312:12) at Module.runMain (module.js:492:10) at process.startup.processNextTick.process._tickCallback (node.js:244:9)

**Comment by sjayanna** [comment]
I made a post on how I got around this issue. Although I didn't fix this bundle but added a separate new command. http://sidjayanna.com/2013/03/13/running-javascript-on-node-from-textmate/
